chore: deprecate edx sphinx theme
edx/platform-plugin-notices pull request #220
Opened 2024-08-06 05:16 UTC by huniafatima-arbi

**Description:**
Describe in a couple of sentences what this PR adds

**Merge checklist:**
- [ ] Bump version
- [ ] Add to changelog
- [ ] Update docs (not only docstrings)

**Post merge:**
(Will eventually be handled via automation)
- [ ] Release with new tag matching version

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

2024-10-30 11:09 UTC, UsamaSadiq requested changes
Let's update the Python version in `tox.ini` and `setuptools` as well. Also it would be better to run `make upgrade` so all requirement files get updated if we're updating the Python version.
Since platform has been updated to Python 3.11, let's update this package to 3.11 or 3.12 as well.

2024-10-30 18:10 UTC, huniafatima-arbi commented
> Let's update the Python version in `tox.ini` and `setuptools` as well. Also it would be better to run `make upgrade` so all requirement files get updated if we're updating the Python version. Since platform has been updated to Python 3.11, let's update this package to 3.11 or 3.12 as well.

@UsamaSadiq python and setuptools version is updated. Please give it a review. 
##### Notes
- codecov is failing in CI due to rate limit. Currently code coverage failure keeps the CI green for the visibility of other tests. Will revert is once PR is approved.  
- Will update release in changelog when the PR is approved.

2024-11-06 07:30 UTC, iamsobanjaved commented on .github/workflows/upgrade-python-requirements.yml
> +        python-version: ["3.12"]
Python requirements upgrade should be done on same version as of edx-platform

2024-11-26 12:44 UTC, UsamaSadiq approved these changes

2024-11-26 13:35 UTC, merged